# Generated by Django 2.0.3 on 2018-04-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardaction',
            name='id',
            field=models.PositiveIntegerField(choices=[(0, 'Premik'), (1, 'WIP omejitev je bila presežena.'), (2, 'Brisanje kartice')], default=0, primary_key=True, serialize=False),
        ),
    ]
