# Generated by Django 2.0.3 on 2018-03-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtype',
            name='name',
        ),
        migrations.AddField(
            model_name='cardtype',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Navadna kartica'), (1, 'Nujna zahteva')], default=0),
        ),
    ]
