# Generated by Django 2.0.3 on 2018-04-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
    ]
