# Generated by Django 2.0.3 on 2018-04-23 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
