# Generated by Django 2.0.3 on 2018-05-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='was_mail_send',
            field=models.BooleanField(default=False),
        ),
    ]
