# Generated by Django 2.0.3 on 2018-05-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_card_was_mail_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='days_to_expire',
            field=models.IntegerField(default=5),
        ),
    ]
