# Generated by Django 2.0.3 on 2018-05-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180423_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cause_of_deletion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
