# Generated by Django 2.0.3 on 2018-05-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.FloatField(null=True),
        ),
    ]
