# Generated by Django 2.0.3 on 2018-03-25 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_columnchild_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnchild',
            name='child',
        ),
        migrations.RemoveField(
            model_name='columnchild',
            name='parent',
        ),
        migrations.AddField(
            model_name='column',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.Column'),
        ),
        migrations.DeleteModel(
            name='ColumnChild',
        ),
    ]
