# Generated by Django 2.0.3 on 2018-05-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180502_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_board_id',
            field=models.IntegerField(default=1),
        ),
    ]
