# Generated by Django 2.0.3 on 2018-05-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_default_board_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_board_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
