# Generated by Django 2.0.3 on 2018-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180503_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_no',
            field=models.IntegerField(null=True),
        ),
    ]
