# Generated by Django 2.0.3 on 2018-05-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_card_card_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_no',
            new_name='card_number',
        ),
    ]
