# Generated by Django 2.0.3 on 2018-05-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180503_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='estimate',
            field=models.FloatField(null=True),
        ),
    ]
