# Generated by Django 2.0.3 on 2018-05-04 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180503_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLogCreateDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_create_delete', to='app.Card')),
            ],
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='action',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
