# Generated by Django 2.0.3 on 2018-05-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180504_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlog',
            name='from_column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_column_log', to='app.Column'),
        ),
    ]
