# Generated by Django 2.0.3 on 2018-04-07 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180403_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='id',
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
