# Generated by Django 2.0.3 on 2018-04-05 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180404_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 10, 15, 50, 1, 394753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 4, 10, 15, 50, 1, 393750, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='roles',
        ),
        migrations.AddField(
            model_name='userteam',
            name='roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TeamRole'),
        ),
    ]
