# Generated by Django 2.0.3 on 2018-04-05 16:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180405_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userteam',
            old_name='roles',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 10, 16, 3, 36, 315051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 4, 10, 16, 3, 36, 313547, tzinfo=utc)),
        ),
    ]
