# Generated by Django 2.0.3 on 2018-04-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180407_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='type',
        ),
    ]
