# Generated by Django 2.0.3 on 2018-04-09 19:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180408_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 19, 40, 9, 655065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='board',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Board'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 4, 14, 19, 40, 9, 654063, tzinfo=utc)),
        ),
    ]
