# Generated by Django 2.0.3 on 2018-04-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180408_1315'),
        ('app', '0017_auto_20180409_1159'),
    ]

    operations = [
    ]
