# Generated by Django 2.0.3 on 2018-03-21 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(default=datetime.date(2018, 3, 26)),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='id',
            field=models.PositiveIntegerField(choices=[(2, 'Naročnik'), (3, 'Kanban Master'), (4, 'Razvijalec')], primary_key=True, serialize=False),
        ),
    ]
