# Generated by Django 2.0.3 on 2018-03-25 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180325_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTeamLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('userteam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserTeam')),
            ],
        ),
    ]
