# Generated by Django 2.0.3 on 2018-03-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180325_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnchild',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='app.Column'),
        ),
    ]
