# Generated by Django 2.0.3 on 2018-03-25 20:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180325_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 20, 50, 18, 336816, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='app.CardType'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 3, 30, 20, 50, 18, 334846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
