# Generated by Django 2.0.3 on 2018-04-01 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180401_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 8, 55, 54, 610245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 4, 6, 8, 55, 54, 609243, tzinfo=utc)),
        ),
    ]
