# Generated by Django 2.0.3 on 2018-04-01 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180401_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 9, 36, 31, 322830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 4, 6, 9, 36, 31, 321827, tzinfo=utc)),
        ),
    ]
