# Generated by Django 2.0.3 on 2018-04-01 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180401_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 10, 0, 51, 614691, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 4, 6, 10, 0, 51, 613187, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
